---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements-roles.yml

driver:
  name: docker
platforms:
  - name: zabbix-server-${MY_MOLECULE_CONTAINER:-mysql-centos}
    image: ${MY_MOLECULE_IMAGE:-"milcom/centos7-systemd"}
    command: ${MY_MOLECULE_DOCKER_COMMAND:-""}
    privileged: True
    networks:
      - name: zabbix
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - ${MY_MOLECULE_GROUP:-mysql}

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: $HOME/.ansible/collections/ansible_collections/community/zabbix
    ANSIBLE_ROLES_PATH: $HOME/.ansible/collections/ansible_collections/community/zabbix/roles
  inventory:
    group_vars:
      mysql:
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
        zabbix_server_dbport: 3306
        zabbix_server_mysql_login_host: mysql-host
        zabbix_server_mysql_login_user: root
        zabbix_server_mysql_login_password: changeme
        zabbix_server_mysql_login_port: 3306
        # zabbix_server_mysql_login_unix_socket: /var/run/mysqld/mysqld.sock
      postgresql:
        zabbix_server_database: pgsql
        zabbix_server_database_long: postgresql
        zabbix_server_pgsql_login_host: postgresql-host
        zabbix_server_pgsql_login_user: postgres
        zabbix_server_pgsql_login_password: changeme

verifier:
  name: testinfra
  lint:
    name: flake8
